# Generated by Django 5.0.6 on 2026-06-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_taggedpost_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedpost',
            name='content_object',
        ),
    ]
